/*
 * tlstunnel -- listen on a UNIX socket, forward to a TLS server.
 *
 * ii speaks plaintext, but supports -u <sockname>. This sits behind that
 * socket and does the TLS, so the IRC client stays 900 lines of C.
 *
 * Trust anchors are COMPILED IN (ta.h, generated by `brssl ta`), not read
 * from a file. That means the set of certificate authorities this machine
 * will believe is covered by dm-verity and the image signature -- nobody can
 * drop an extra CA into a directory. A normal distro trusts ~150 roots; this
 * trusts exactly the ones we chose.
 */
#include <sys/socket.h>
#include <sys/un.h>
#include <netinet/in.h>
#include <netinet/tcp.h>
#include <netdb.h>
#include <poll.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include <signal.h>

#include "bearssl.h"
#include "ta.h"

static int
tcp_connect(const char *host, const char *port)
{
	struct addrinfo hints, *ai, *p;
	int fd = -1, e;

	memset(&hints, 0, sizeof hints);
	hints.ai_family = AF_UNSPEC;
	hints.ai_socktype = SOCK_STREAM;
	if ((e = getaddrinfo(host, port, &hints, &ai)) != 0) {
		fprintf(stderr, "tlstunnel: resolve %s: %s\n", host, gai_strerror(e));
		return -1;
	}
	for (p = ai; p; p = p->ai_next) {
		if ((fd = socket(p->ai_family, p->ai_socktype, p->ai_protocol)) < 0)
			continue;
		if (connect(fd, p->ai_addr, p->ai_addrlen) == 0)
			break;
		close(fd);
		fd = -1;
	}
	freeaddrinfo(ai);
	if (fd >= 0) {
		int one = 1;
		setsockopt(fd, IPPROTO_TCP, TCP_NODELAY, &one, sizeof one);
	}
	return fd;
}

static int
unix_listen(const char *path)
{
	struct sockaddr_un sa;
	int fd;

	if (strlen(path) >= sizeof sa.sun_path) {
		fprintf(stderr, "tlstunnel: socket path too long\n");
		return -1;
	}
	unlink(path);
	memset(&sa, 0, sizeof sa);
	sa.sun_family = AF_UNIX;
	strcpy(sa.sun_path, path);
	if ((fd = socket(AF_UNIX, SOCK_STREAM, 0)) < 0)
		return -1;
	if (bind(fd, (struct sockaddr *)&sa, sizeof sa) < 0 || listen(fd, 1) < 0) {
		close(fd);
		return -1;
	}
	return fd;
}

/*
 * Pump bytes between a local plaintext fd and the TLS engine until either
 * side closes. This drives the engine directly rather than using br_sslio,
 * because sslio blocks in one direction and a tunnel needs both at once.
 */
static int
pump(br_ssl_client_context *cc, int tcp, int local)
{
	unsigned char *buf;
	size_t len;
	struct pollfd fds[2];

	for (;;) {
		unsigned st = br_ssl_engine_current_state(&cc->eng);
		int nf = 0, tcp_ev = 0, loc_ev = 0;

		if (st & BR_SSL_CLOSED) {
			int err = br_ssl_engine_last_error(&cc->eng);
			if (err != BR_ERR_OK) {
				fprintf(stderr, "tlstunnel: ssl error %d\n", err);
				return 1;
			}
			return 0;
		}
		if (st & BR_SSL_SENDREC) tcp_ev |= POLLOUT;
		if (st & BR_SSL_RECVREC) tcp_ev |= POLLIN;
		if (st & BR_SSL_SENDAPP) loc_ev |= POLLIN;
		if (st & BR_SSL_RECVAPP) loc_ev |= POLLOUT;

		if (tcp_ev) { fds[nf].fd = tcp; fds[nf].events = tcp_ev; fds[nf].revents = 0; nf++; }
		if (loc_ev) { fds[nf].fd = local; fds[nf].events = loc_ev; fds[nf].revents = 0; nf++; }
		if (nf == 0) return 0;

		if (poll(fds, nf, -1) < 0) {
			if (errno == EINTR) continue;
			return 1;
		}

		for (int i = 0; i < nf; i++) {
			short re = fds[i].revents;
			if (!re) continue;

			if (fds[i].fd == tcp && (re & POLLOUT) && (st & BR_SSL_SENDREC)) {
				buf = br_ssl_engine_sendrec_buf(&cc->eng, &len);
				ssize_t n;
				do { n = write(tcp, buf, len); } while (n < 0 && errno == EINTR);
				if (n <= 0) return 1;
				br_ssl_engine_sendrec_ack(&cc->eng, n);
			}
			if (fds[i].fd == tcp && (re & (POLLIN | POLLHUP)) && (st & BR_SSL_RECVREC)) {
				buf = br_ssl_engine_recvrec_buf(&cc->eng, &len);
				ssize_t n = read(tcp, buf, len);
				if (n <= 0) { br_ssl_engine_close(&cc->eng); continue; }
				br_ssl_engine_recvrec_ack(&cc->eng, n);
			}
			if (fds[i].fd == local && (re & (POLLIN | POLLHUP)) && (st & BR_SSL_SENDAPP)) {
				buf = br_ssl_engine_sendapp_buf(&cc->eng, &len);
				ssize_t n = read(local, buf, len);
				if (n <= 0) { br_ssl_engine_close(&cc->eng); continue; }
				br_ssl_engine_sendapp_ack(&cc->eng, n);
				br_ssl_engine_flush(&cc->eng, 0);
			}
			if (fds[i].fd == local && (re & POLLOUT) && (st & BR_SSL_RECVAPP)) {
				buf = br_ssl_engine_recvapp_buf(&cc->eng, &len);
				ssize_t n;
				do { n = write(local, buf, len); } while (n < 0 && errno == EINTR);
				if (n <= 0) return 1;
				br_ssl_engine_recvapp_ack(&cc->eng, n);
			}
		}
	}
}

/* stdio variant: read side is fd 0, write side is fd 1 */
static int
pump_stdio(br_ssl_client_context *cc, int tcp)
{
	unsigned char *buf;
	size_t len;
	struct pollfd fds[2];

	for (;;) {
		unsigned st = br_ssl_engine_current_state(&cc->eng);
		int nf = 0, tcp_ev = 0;
		int want_in = 0, want_out = 0;

		if (st & BR_SSL_CLOSED) {
			int err = br_ssl_engine_last_error(&cc->eng);
			if (err != BR_ERR_OK) {
				fprintf(stderr, "tlstunnel: ssl error %d\n", err);
				return 1;
			}
			return 0;
		}
		if (st & BR_SSL_SENDREC) tcp_ev |= POLLOUT;
		if (st & BR_SSL_RECVREC) tcp_ev |= POLLIN;
		if (st & BR_SSL_SENDAPP) want_in = 1;
		if (st & BR_SSL_RECVAPP) want_out = 1;

		if (tcp_ev) { fds[nf].fd = tcp; fds[nf].events = tcp_ev; fds[nf].revents = 0; nf++; }
		if (want_in) { fds[nf].fd = 0; fds[nf].events = POLLIN; fds[nf].revents = 0; nf++; }
		if (nf == 0 && !want_out) return 0;

		if (want_out) {
			buf = br_ssl_engine_recvapp_buf(&cc->eng, &len);
			ssize_t n;
			do { n = write(1, buf, len); } while (n < 0 && errno == EINTR);
			if (n <= 0) return 1;
			br_ssl_engine_recvapp_ack(&cc->eng, n);
			continue;
		}
		if (poll(fds, nf, -1) < 0) {
			if (errno == EINTR) continue;
			return 1;
		}
		for (int i = 0; i < nf; i++) {
			short re = fds[i].revents;
			if (!re) continue;
			if (fds[i].fd == tcp && (re & POLLOUT) && (st & BR_SSL_SENDREC)) {
				buf = br_ssl_engine_sendrec_buf(&cc->eng, &len);
				ssize_t n;
				do { n = write(tcp, buf, len); } while (n < 0 && errno == EINTR);
				if (n <= 0) return 1;
				br_ssl_engine_sendrec_ack(&cc->eng, n);
			}
			if (fds[i].fd == tcp && (re & (POLLIN | POLLHUP)) && (st & BR_SSL_RECVREC)) {
				buf = br_ssl_engine_recvrec_buf(&cc->eng, &len);
				ssize_t n = read(tcp, buf, len);
				if (n <= 0) { br_ssl_engine_close(&cc->eng); continue; }
				br_ssl_engine_recvrec_ack(&cc->eng, n);
			}
			if (fds[i].fd == 0 && (re & (POLLIN | POLLHUP)) && (st & BR_SSL_SENDAPP)) {
				buf = br_ssl_engine_sendapp_buf(&cc->eng, &len);
				ssize_t n = read(0, buf, len);
				if (n <= 0) { br_ssl_engine_flush(&cc->eng, 0); continue; }
				br_ssl_engine_sendapp_ack(&cc->eng, n);
				br_ssl_engine_flush(&cc->eng, 0);
			}
		}
	}
}

int
main(int argc, char **argv)
{
	br_ssl_client_context sc;
	br_x509_minimal_context xc;
	unsigned char iobuf[BR_SSL_BUFSIZE_BIDI];
	int lfd, cfd, tfd, rc;

	if (argc != 4) {
		fprintf(stderr, "usage: tlstunnel <unix-socket|-> <host> <port>\n");
		return 2;
	}
	signal(SIGPIPE, SIG_IGN);

	/* "-" pipes stdio through TLS instead of listening, which makes the
	 * tunnel scriptable and testable without a socket client. */
	if (!strcmp(argv[1], "-")) {
		if ((tfd = tcp_connect(argv[2], argv[3])) < 0)
			return 1;
		br_ssl_client_init_full(&sc, &xc, TAs, TAs_NUM);
		br_ssl_engine_set_buffer(&sc.eng, iobuf, sizeof iobuf, 1);
		br_ssl_client_reset(&sc, argv[2], 0);
		rc = pump_stdio(&sc, tfd);
		close(tfd);
		return rc;
	}

	if ((lfd = unix_listen(argv[1])) < 0) {
		perror("tlstunnel: listen");
		return 1;
	}

	for (;;) {
		if ((cfd = accept(lfd, NULL, NULL)) < 0) {
			if (errno == EINTR) continue;
			perror("tlstunnel: accept");
			return 1;
		}
		if ((tfd = tcp_connect(argv[2], argv[3])) < 0) {
			close(cfd);
			continue;
		}

		/* full profile + our compiled-in trust anchors, so the server
		 * certificate must chain to one of them or the handshake fails */
		br_ssl_client_init_full(&sc, &xc, TAs, TAs_NUM);
		br_ssl_engine_set_buffer(&sc.eng, iobuf, sizeof iobuf, 1);
		br_ssl_client_reset(&sc, argv[2], 0);

		rc = pump(&sc, tfd, cfd);
		close(tfd);
		close(cfd);
		if (rc) fprintf(stderr, "tlstunnel: session ended with error\n");
	}
	return 0;
}
